### PR TITLE
Estonian update

### PR DESCRIPTION
**Pull request by Madis0**
Added more strings for Estonian :)

### CODE REVIEW

**Comment by Madis0** [comment]
Could you review this and tell me what did I do wrong to get a failing check? @jbarrett 

I followed the same approach as in #240 - download latest from master, translate with [localize.biz](https://localise.biz/free/poeditor) and upload to GitHub.

**Comment by jbarrett** [comment]
Hi @Madis0! The failure is due to Windows line endings in the file duckduckgo.po.

For the last PR I fixed these manually, but haven't had a chance to do that this time - sorry for the delay!

Is there an option for line endings in localize.biz? Or have you opened it in another editor before uploading? The files should have Unix line endings, if you see an option for that.

**Comment by Madis0** [comment]
@jbarrett Could you have another look? I tried recreating the file with Unix-style endings several times, but the checks still fail.

The error seems to be

> t/00-build.t ... 1/? duckduckgo.po:3230: 'msgid' and 'msgstr' entries do not both end with '\n'

but I don't get it - they did not have `\n` in the first place?

**Comment by jbarrett** [comment]
@Madis0 Looks like a literal "\n" snuck into [this translation](https://github.com/duckduckgo/duckduckgo-locales/blob/1bd1ff2/locales/et_EE/LC_MESSAGES/duckduckgo.po#L3231). I took the liberty of fixing it.

Many thanks for these translations and for taking the time to fix up the PO file!

**Pull request merged**
