### PR TITLE
Update translations and add untranslated words

### PR DESCRIPTION
**Pull request by akanshgulati**
1. Updated the sentences to make sense. 
2. Updated `DuckDuckGo` in different type case or in Hindi language to `DuckDuckGo`.
3. Updated the spacing in some string. 
4. Removed dot (.) from the strings in Hindi language, used `।` instead to end the sentence.
5. Removed `\t` from the strings.

### CODE REVIEW

**Comment by akanshgulati** [comment]
@jbarrett Any update here?

**Comment by jbarrett** [comment]
Hi @akanshgulati! Many thanks for this update! Very sorry for the delay in responding.

While we're working on communicating a consistent policy for this, we prefer to leave 'DuckDuckGo' untranslated since it is our registered trade mark. Leaving trade marks untranslated is also how I've observed other sites do it.

**Comment by akanshgulati** [comment]
@jbarrett Okay, adding the fix for atleast Hindi as per your latest PR #197

**Comment by jbarrett** [comment]
Thank you @akanshgulati!

Sorry for the delays in my review.

**Pull request merged**
