### PR TITLE
duckduckgo.po

### PR DESCRIPTION
**Pull request by Anonymouss76**
**Updated** Serbian language

### CODE REVIEW

**Comment by GioSensation** [comment]
Hey @Anonymouss76! Thanks for your contribution. Do you mind updating the existing file with your changes, instead of creating a new file as you did here? Thanks!

Also note that:
- Our brand name should be left untranslated and in latin characters
- There are two strings where we commented "Do not change". Please leave them unchanged 😉

Thanks!

**Comment by Anonymouss76** [comment]
> Hey @Anonymouss76! Thanks for your contribution. Do you mind updating the existing file with your changes, instead of creating a new file as you did here? Thanks!
> 
> Also note that:
> 
>     * Our brand name should be left untranslated and in latin characters
> 
>     * There are two strings where we commented "Do not change". Please leave them unchanged 😉
> 
> 
> Thanks!

I am new here. Can you tell me how to update exisiting file? I updated file in online PO editor. After that I delleted ALL code and copied my new PO file. Here is my new updated file:
[messages-sr_RS.zip](https://github.com/duckduckgo/duckduckgo-locales/files/7628211/messages-sr_RS.zip)

**Comment by GioSensation** [comment]
> > Hey @Anonymouss76! Thanks for your contribution. Do you mind updating the existing file with your changes, instead of creating a new file as you did here? Thanks!
> > Also note that:
> > ```
> > * Our brand name should be left untranslated and in latin characters
> > 
> > * There are two strings where we commented "Do not change". Please leave them unchanged 😉
> > ```
> >   
> > Thanks!
> 
> I am new here. Can you tell me how to update exisiting file? I updated file in online PO editor. After that I delleted ALL code and copied my new PO file. Here is my new updated file: [messages-sr_RS.zip](https://github.com/duckduckgo/duckduckgo-locales/files/7628211/messages-sr_RS.zip)

You can copy/paste your content into the existing file, or delete the existing file and rename yours `duckduckgo.po`. Let me know if this doesn't help.

**Comment by GioSensation** [comment]
Nevermind, I see you've opened #506. I'm closing this, but feel free to reopen if needed.

**Pull request closed without merging**
