### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by b9a1**

### CODE REVIEW

**Comment by b9a1** [comment]
@GioSensation, I skimmed through the ‘professional’ translations, but at least for `zh_CN`, no substantial improvements have been made. Some errors still need correction, and my changes in #371 have been reverted. Maybe I could do some cherry‐picking before another force‐push, but are PRs still welcomed?

**Comment by GioSensation** [comment]
@b9a1 Thanks for looking into this further.

This first pass was only to complete the missing strings. Soon we will launch a thorough review and harmonisation of language usage across all languages, but that will take some time. In any case, we still very much welcome community contributions.

If you're able to resolve the conflicts, I'm happy to look into this and merge. My apologies for not being able to review this sooner and thanks again for your contribution. It's much appreciated.

**Comment by b9a1** [comment]
OK, I’ll wait for the harmonization to take place first, then. Dealing with the conflicts would also take some time.

**Comment by b9a1** [comment]
@GioSensation, I’m almost ready to push my changes. (Is it a good time, though? I don’t want any more regressions.) But there is a string I couldn’t find on the website:
https://github.com/duckduckgo/duckduckgo-locales/blob/0637a2be8ec04a74488d5a652007addd956fae26/duckduckgo.pot#L378-L383
Could you point out where to find it?

**Comment by GioSensation** [comment]
@b9a1 Thanks for your message. We continue pushing changes as we add new strings or change old ones. The good news is that we have fixed the problem with community strings being overwritten, so you are welcome to push your contributions and we will integrate them. 🎉 

That specific string is not currently shown on the website. Let me know if I can help with anything.

Thank you.

**Comment by b9a1** [comment]
Thanks for the information. This PR is now ready for review.

**Comment by GioSensation** [comment]
Thanks for your patience @b9a1. Much appreciated. Merging now.

**Pull request merged**
