### PR TITLE
Added few translations and changed one token.

### PR DESCRIPTION
**Pull request by preemeijer**
Added few translations and changed one token.

### CODE REVIEW

**Comment by preemeijer** [comment]
Hello, I do see know that there are conflicts. Can I do something about this? Because I did not see this when I made the pull request. Sorry for that.
Cheers, Paul

**Comment by GioSensation** [comment]
Hi Paul. First of all, thanks for your contribution. Unfortunately, your `.po` editor reformatted the whole file, which makes it quite hard to handle. If you are using Poedit, you can adjust the `Wrap at` setting. In this screenshot you can see the settings I have locally, which I think are the default.

Screenshot 2020-09-09 at 07 33 21

You can try playing around with those settings and checking the diffs to see if they look any better. If you need further help let me know. I am assigning this back to you.

**Comment by preemeijer** [comment]
I've looked at the settings but I've got the exact same setting but on a Linux machine and have never been changed by me.
Screenshot_20200927_203631

**Comment by preemeijer** [comment]
What I'm seeing is that I've used a newer version of poedit. Maybe that is the case here?

**Comment by preemeijer** [comment]
@GioSensation I've unchecked the option "Preserve formatting of existing files" and this is way much better to review.
Can you please check that you think the same about it.

**Comment by preemeijer** [comment]
Can someone please have a look? Cheer, Paul

**Comment by GioSensation** [comment]
Hi @preemeijer. Apologies for taking so long to get to this. Currently the branch has conflicts with the `master` branch. Do you mind resolving them checking back with me if there are issues? Once you're done, I'll get to it right away. Thanks for your patience and your contribution.

**Comment by preemeijer** [comment]
I remove this pull request; I think that is better.

**Pull request closed without merging**
