### PR TITLE
Added Santali language (sat_IN) support

### PR DESCRIPTION
**Pull request by Prasanta-Hembram**
Hi, I have added Santali language support. I hope my files and changes are error free.

### CODE REVIEW

**Comment by Prasanta-Hembram** [comment]
Need some help re-review the translation in Santali (Ol Chiki), i have checked it's ok from my side but still not 200% sure. I have emailed 2 more proofreaders but they are busy right now. Are you all @Chakulu-Hembram @Bisuz @SantarhKora @Haripadahembram available right now??. I hope everyone is good:-)). Recently localized duckduckgo for Santali language, after completing it i have created this pull, this pull will soon be merged but then also i want to get suggestions/correction in translation from you all.

**Comment by Chakulu-Hembram** [comment]
@Prasanta-Hembram give me some time to review it and i shall comment here after completing my review for the translation. Translations are mostly ok. I will dive deep into these.

**Comment by Prasanta-Hembram** [comment]
> @Prasanta-Hembram give me some time to review it and i shall comment here after completing my review for the translation. Translations are mostly ok. I will dive deep into these.

Thanks @Chakulu-Hembram , for being here in time :-)) ... and sorry about doing it so fast. You can take your time.

**Comment by Prasanta-Hembram** [comment]
Hi, @GioSensation i have tried all my best to bring Santali language translation to Duckduckgo, I'm fearing that you may not be accepting new locale (just my assumption, i may be wrong), if that is the case then there is no issue. I should have asked before proceeding for the translation though. If you are not accepting new locale (no issue) then i shall ask my proofreader friends to break off :-). If new locale addition is allowed then is there any way to test before making a release.

**Comment by GioSensation** [comment]
Hi, @Prasanta-Hembram. Thanks for your contribution here. We haven't added a locale for quite a while. We're looking into this and will let you know.

**Comment by GioSensation** [comment]
@Prasanta-Hembram I've merged this to test the language on our dev machines. Unfortunately these are not accessible to the general public, but I have taken a screenshot. How does this look to you?

CleanShot 2022-03-26 at 08 44 53@2x

I will revert this merge shortly while we discuss this further internally. In the meantime let me know what you think of that screenshot. Of course you will be able to refine the translations over time after release.

**Comment by Prasanta-Hembram** [comment]
Wow !!! Thanks @GioSensation . The screenshot looks good to me, fonts, font size and strings are fine only. 👍👍Just showed it to my peers they too are happy 😊 . 

Regarding translation, i have repeatedly previewed my translations and many more are volunteering for the proofreading, so the quality is going to be solid. Though, there are no machine translation for Santali language so crosschecking is not possible for a non-native speaker :-\. I have been trying to improve Apertium for eng-sat pair, but still in beta (https://beta.apertium.org/index.eng.html#?dir=eng-sat&q=India). In Google Translate too Santali language is in beta . 

So for now you have to trust on us :-).

**Comment by Prasanta-Hembram** [comment]
> screenshot

looks good to me.

**Comment by Chakulu-Hembram** [comment]
Santali texts in the screenshot are fine. Not too small/vry big. Perfect 👍👍👍

**Comment by Prasanta-Hembram** [comment]
Santali language is one of the 22 official languages of India, and Indian Government has made a mendatory inclusion of all those 22 languages by any digital means. Though for now it has mandated only for [Computer/Mobile applications](https://unicode-org.atlassian.net/browse/CLDR-11935?jql=text%20~%20%22santali%22) for use only in India. Maybe in future it may be mandated for Websites but not mandated for now, so taking advantage to volunteer.

> your expectations and the use case.

I want people should get content in Santali language with UI in Santali language. Not that people should search english content.

In India there are government exams conducted in this languages, taught in school has it's own Wikipedia (https://sat.wikipedia.org/ - with more than 5000 articles) and much more content. There are plenty of contents available for Santali language and are still growing. But unfortunately it's not discovered by some engines.

I have also opeaned an issue related to Santali language which is non-discoverd by Duckduckgo https://github.com/duckduckgo/duckduckgo-locales/issues/522 . But, various search engines are providing good helpful results. 

With a small research i have found plenty of search engines which gives relevent search results. Google gives the best relevent result till now and other 10. I have tested with 12 search engine with "ᱥᱟᱱᱛᱟᱲᱤ" or "ᱚᱞ ᱪᱤᱠᱤ" as query.  
Example:

1. https://qmamu.com/search?q=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&from=web
2. [https://www.google.com/search?q=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&sxsrf=APq-WBudJGMzblnW4-iO4abECOiZDjo1ug%3A1646373836075&source=hp&ei=zKshYpGCAo6ImAXH1IO4Cg&iflsig=AHkkrS4AAAAAYiG53MFJqHO4-Lj6_EhjN-uuv5ObTRU_&ved=0ahUKEwiRmKi95Kv2AhUOBKYKHUfqAKcQ4dUDCAc&uact=5&oq=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&gs_lcp=Cgdnd3Mtd2l6EANQAFiYFWC3GmgBcAB4AIAB7wGIAZAOkgEFMC40LjWYAQCgAQE&sclient=gws-wiz](https://www.google.com/search?q=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&sxsrf=APq-WBudJGMzblnW4-iO4abECOiZDjo1ug%3A1646373836075&source=hp&ei=zKshYpGCAo6ImAXH1IO4Cg&iflsig=AHkkrS4AAAAAYiG53MFJqHO4-Lj6_EhjN-uuv5ObTRU_&ved=0ahUKEwiRmKi95Kv2AhUOBKYKHUfqAKcQ4dUDCAc&uact=5&oq=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&gs_lcp=Cgdnd3Mtd2l6EANQAFiYFWC3GmgBcAB4AIAB7wGIAZAOkgEFMC40LjWYAQCgAQE&sclient=gws-wiz&authuser=0)
3. https://www.ask.com/web?q=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&ad=dirN&o=0
4. https://petalsearch.com/search?query=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&channel=all&locale=en-us&sregion=in&from=PCweb&ps=10&pn=1&ss_mode=moderate&sid=9m559whdje3w0aet2vjejod89r5mh2e7&ml=en-us&uuid=8fji4x1vldgybnm46i2vo35z7fooym75&qs=1&source=PCweb&page_start=0
5. https://searx.be/search (https://searx.space/)
6. https://www.startpage.com/sp/search (YES)
7. https://www.lukol.com/s.php?q=%E1%B1%9C%E1%B1%A9%E1%B1%9C%E1%B1%9A%E1%B1%9E+%E1%B1%9B%E1%B1%9A%E1%B1%A8%E1%B1%A1%E1%B1%9A%E1%B1%A2%E1%B1%9F#gsc.tab=0&gsc.q=%E1%B1%9C%E1%B1%A9%E1%B1%9C%E1%B1%9A%E1%B1%9E%20%E1%B1%9B%E1%B1%9A%E1%B1%A8%E1%B1%A1%E1%B1%9A%E1%B1%A2%E1%B1%9F&gsc.page=1
8. https://search.yahoo.co.jp/search?p=%E1%B1%9C%E1%B1%A9%E1%B1%9C%E1%B1%9A%E1%B1%9E+%E1%B1%9B%E1%B1%9A%E1%B1%A8%E1%B1%A1%E1%B1%9A%E1%B1%A2%E1%B1%9F&fr=top_ga1_sa&ei=UTF-8&ts=4544&aq=-1&oq=&at=&ai=282a12f0-3c69-477c-85e6-81ff22ba8094

Semi results:

1. https://www.mojeek.com/search?q=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4
2. https://searx.space/
3. https://yandex.com/search/?text=%E1%B1%A5%E1%B1%9F%E1%B1%B1%E1%B1%9B%E1%B1%9F%E1%B1%B2%E1%B1%A4&lr=21229

I know it is a low resource language but it's utility is remarkably increased. Maybe you can think of it in future. I have no problem if it is not included in Duckduckgo. :-)

**Comment by Cloud-Prakash** [comment]
@GioSensation Hello.. I am a member from Prasanta-Hembram translation team. I wanted to point out that you have typed the query in english. If the query was typed in santali most of the result returned would be in santali and few in english or hindi. I have checked it with google.

**Comment by Cloud-Prakash** [comment]
DuckDuckGo does not return any results but Google does.I don't know what queries you tested @GioSensation but i request you to test this query in Google ᱨᱟᱺᱪᱤ, ᱡᱷᱟᱨᱠᱷᱚᱱᱰ. There are results in Santali which are uself to the reader.

**Comment by GioSensation** [comment]
Thank you all for your submission and comments.

After internal review, we will not be able to add support for the Santali language to our UI at this time. Our search engine doesn't support queries in the Santali language and the Ol Chiki Script. Even if the UI is translated, users may be confused because they will not be able to perform localized searches using that language.

If we intend to add support in the future, we may revive this PR and ask for your input.

**Pull request merged**
