### PR TITLE
Update zh_CN translation

### PR DESCRIPTION
**Pull request by b9a1**
Some questions about the new tokens:
```PO
msgid "Customize DuckDuckGo"
msgid "Personalize DuckDuckGo"
msgid "Prompt me to customize my DuckDuckGo experience."
msgid "Prompt me to personalize my DuckDuckGo experience."
```
What’s the difference between ‘customize’ and ‘personalize’?
```PO
msgid "Show most visited links on new tab page"
```
New tab page of the browser? How could DuckDuckGo control that page?

### CODE REVIEW

**Comment by jbarrett** [comment]
Thank you @b9a1! Sorry for the delay in responding. I've ping the developers for further info on these strings - hopefully should have a response later today.

**Comment by gtfiorentino** [comment]
Hi @b9a1! The new tab page is a browser feature that Chromium browsers allow the default search engine to control. DuckDuckGo was recently added as a default search engine option, and so we are in the process of creating the new tab page that users will see when they set DuckDuckGo as their default. You can see a preview in a [beta version of Chrome](https://www.chromium.org/getting-involved/dev-channel), and we expect the page to be available to everyone in Chrome 75.

**Comment by b9a1** [comment]
@gtfiorentino That’s awesome, thank you!

Since I don’t see the customize/personalize options in the current Settings page, I’ll update the rest of new tokens first.

**Comment by jbarrett** [comment]
Thank you @b9a1! There is no effective difference between "personalize" and "customize" but since those tokens are no longer used, they should be cleaned up soon anyway.

:+1:

**Pull request merged**
