### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by a-polivanchuk**

### CODE REVIEW

**Comment by GioSensation** [comment]
Hey @a-polivanchuk! Thanks for your help again. This branch now has conflicts and cannot be merged. Do you mind taking a look and resolving them? Thanks!

**Comment by a-polivanchuk** [comment]
Hi @GioSensation initially, there were no any conflicts in this PR. I reviewed the conflicts and it seems they're related to the file change. I see file has been updated with 61 new strings.
So I'll review it and either update this PR or create new one. Let me have some time for doing that.

**Comment by a-polivanchuk** [comment]
@GioSensation I submitted the next update for this PR but it seems that you've recently pushed the translations after my PR in 3a8999d86c2c0529eb2db3ceb56d002216aeba57. That's why the conflicts appeared.
Could you please clarify the source of those translations, so I can either import them into my workflow or you'll need to overwrite.
Thanks

**Comment by GioSensation** [comment]
They come from our translation service. Ukranian is one of the languages covered there. I do my best to upload your proposals to the platform, so your changes should be reflected on both sides, but in this case there was a timing issue and I imported them while your PR was already open.

**Comment by a-polivanchuk** [comment]
@GioSensation thanks for the clarification. Considering that, I'm closing this PR and opening new one #519 with revised translations based on the latest source file keeping the changes from the translation service.

**Pull request closed without merging**
