### PR TITLE
Fixes for mis-translations in Canadian French

### PR DESCRIPTION
**Pull request by tagawa**
Thanks to a user for pointing this out.

### CODE REVIEW

**Comment by moollaza** [comment]
@tagawa unfortunately my skills are pretty lacking these days. I would rely on someone else, perhaps @AdamSC1-ddg or @bbraithwaite?

**Comment by tagawa** [comment]
Understood.

@bbraithwaite , are you a suitable candidate for reviewing this please?

**Comment by jbarrett** [comment]
These are a clear improvement - merging.

**Comment by bbraithwaite** [comment]
Sorry I missed this one!

**Pull request merged**
